### ISSUE TITLE
Bivariate analysis

### ISSUE THREAD

**Issue by Tuclly** [SubratoChakravorty/ECE-229-Group5-final-project#12]
### Draw the box plot  and histogram (option for the user in the graph )for the following variables:
Y-axis is **X1SCIEFF ‘Scale of Student’s Science Self-Efficacy’**(one variable in a window)
X-axis could be the following:(another window which could be dragged down to choose variables)

**1.~ X1SEX : Student’s Gender** 
![image](https://user-images.githubusercontent.com/57241074/82284883-ec595e00-994e-11ea-9618-67835d34e8a0.png)
**2. ~ X1CONTROL ‘School Control’(public or private?)**
![image](https://user-images.githubusercontent.com/57241074/82285010-3e01e880-994f-11ea-9a7c-3c9e9335a68e.png)
**3. ~ N1SEX ‘Science Teacher’s Sex’**
![image](https://user-images.githubusercontent.com/57241074/82285054-58d45d00-994f-11ea-9fed-2a2cd36af4ec.png)
**4. ~ teacher previously held science job(which is not plotted in 143 proj)**
From the thesis, we know Y and X has a strong relationship.
**5.~ X1RACE: Student’s Race**
**6.~NICOURSE ‘Student’s fall 2009 science course’**
![image](https://user-images.githubusercontent.com/57241074/82285437-50305680-9950-11ea-8719-123a08492f0c.png)

**7.~XILOCALE ‘School Locale (Urbanicity)’**
![image](https://user-images.githubusercontent.com/57241074/82285403-41e23a80-9950-11ea-993f-8551c016be85.png)

The school location could also be graphed in a live map of the whole us if the data of location could be shown in the map(has some Latitude and longitude information) like this:
![image](https://user-images.githubusercontent.com/57241074/82285563-908fd480-9950-11ea-889e-73dde7072f07.png)
**Link:**[https://dash-gallery.plotly.host/dash-oil-gas-ternary/](url)

**8.~ ‘teacher’s highest degree earned’**
**9~ Scale of teacher attitude** 
The attitude can be made up of some 6 or 7 variables, we could make a graph like that:
![image](https://user-images.githubusercontent.com/57241074/82285670-d9478d80-9950-11ea-8d02-41cfef0e2f95.png)
And the variables like labels could also be shown in the nearby like this:
![image](https://user-images.githubusercontent.com/57241074/82285799-19a70b80-9951-11ea-8662-0223648a92b3.png)
Which will tell the user what variables they have chosen and abandon or add some variables as they want.
This graph can also be applied in the following multivariate analysis
Link:[https://dash-gallery.plotly.host/dash-clinical-analytics/](url)

**Comment by Ian-Mint** [comment]
broke this out into separate issues:
issue #19 ,
issue #20,

The box plot has been implemented on branch `bivariate`
