### ISSUE TITLE
Multivariate analysis

### ISSUE THREAD

**Issue by Tuclly** [SubratoChakravorty/ECE-229-Group5-final-project#13]
Multivariate analysis can be very fancy and cool from I have collected from the dashboard gallery, I will show you the output graph and the corresponding link:

**1. Extend the bivariate analysis to multivariate analysis, expand one dimension of the graph with one more variable, and the 2D scatter is also important for the user to compare any two variables in this 3D Scatter:** 
![image](https://user-images.githubusercontent.com/57241074/82290251-50821f00-995b-11ea-94ef-42601d20ed23.png)
Link:[https://dash-gallery.plotly.host/dash-drug-discovery/](url)

**2. As we talked about in the bivariate analysis, the location of the school can be shown in the map if possible, and meanwhile, the user could choose the label(or filter) to see where and what they are(like geological information, east or west or north-east, or the control of the school like the private or public. Like this:**
![image](https://user-images.githubusercontent.com/57241074/82290467-d9995600-995b-11ea-9154-4f7205e2bfb0.png)
Link:[https://dash-gallery.plotly.host/dash-oil-gas-ternary/](url)

**3. When many variables compare with each other, for one specific variable, it may have a different relationship with other variables, we could draw a matrix graph like heat map which like this: **
![image](https://user-images.githubusercontent.com/57241074/82290831-a6a39200-995c-11ea-8bf5-d3e250349747.png)
[https://dash-gallery.plotly.host/dash-clinical-analytics/](url)

**For example,**  X1SES ‘Socio-economic status composite has different relationships between other variables like : 

- ~  cost perception

- ~ X1SCIEFF ‘Scale of Student’s Science Self-Efficacy’  

- X1SCIID ‘Scale of student's science identity

- X1SCIUTI ‘Scale of student's science utility’

- X1SCIINT ‘Scale of student's interest in fall 2009 science course

**And also, ‘Scale of student's science identity' has some relationship with other the same variables like:** 

- ~ X1SCIEFF ‘Scale of Student’s Science Self-Efficacy’ 

- X1SCIUTI ‘Scale of student's science utility’

- X1SCIINT ‘Scale of student's interest in fall 2009 science course

- ~  cost perception

Therefore, we could make a large correlation matrix for variables the user choose in the x and y-axis and form the graph like a heatmap to show how these variables could be related to each other. 
**4. **
The scale of teacher attitude created from 7 variables: 

- S1STCHVALUES ‘9th grader's fall 2009 science teacher values/listens to students' ideas’ 
- S1STCHRESPCT ‘9th grader's fall 2009 science teacher treats students with respect’ 
- S1STCHFAIR ‘9th grader's fall 2009 science teacher treats every student fairly’ 
- S1STCHCONF ‘9th grader's fall 09
- science teacher thinks all students can be successful’ 
- S1STCHMISTKE ‘9th grader's fall 09 science teacher think mistakes OK if students learn’ 
- S1STCHTREAT ‘9th grader's fall 09 science teacher treats some kids better than others’

So, the **X1SCIEFF ‘Scale of Student’s Science Self-Efficacy’** could also be built a correlation matrix with the above variables, or just like the 143 proj graph:
![image](https://user-images.githubusercontent.com/57241074/82291627-3433b180-995e-11ea-8a03-c7a522ac80f7.png)

---------------------------------------------------------------------------------

**Comment by Ian-Mint** [comment]
@Tuclly :
Please make **1.** a new issue and explain it more clearly
**2.** covered by issue #19 
**3.** covered by issue #20 

please add new issues for anything I've missed and comment any corrections on the existing issues.
