### ISSUE TITLE
Unify capitalization in variables.csv

### ISSUE THREAD

**Issue by Ian-Mint** [SubratoChakravorty/ECE-229-Group5-final-project#16]
Some of the short desctiptions are "First *S*econd" and others are "First *s*econd". They should all be the same, may just capitalize the first word.

e.g.
![image](https://user-images.githubusercontent.com/6959555/82360709-a20fc580-99be-11ea-97da-3228c9e79fbc.png)

**Comment by Ian-Mint** [comment]
The same thing goes for the long descriptions.

**Comment by SubratoChakravorty** [comment]
Done!
