### ISSUE TITLE
Show school locations

### ISSUE THREAD

**Issue by Ian-Mint** [SubratoChakravorty/ECE-229-Group5-final-project#19]
The school location could also be graphed in a live map of the whole us if the data of location could be shown in the map(has some Latitude and longitude information) like this:

![image](https://user-images.githubusercontent.com/6959555/82381310-d4311f80-99de-11ea-8ead-491d12c6eef7.png)

Link:https://dash-gallery.plotly.host/dash-oil-gas-ternary/

**Comment by SubratoChakravorty** [comment]
I am not sure whether the data has longitude and latitude info

**Comment by Ian-Mint** [comment]
Yeah, probably not. I think this is a wish-list item for now

**Comment by Ian-Mint** [comment]
I'm closing this, this isn't going to be happening
