### ISSUE TITLE
Provide names of each category for the categorical data

### ISSUE THREAD

**Issue by Ian-Mint** [SubratoChakravorty/ECE-229-Group5-final-project#2]
Slack seems to be down, so I'm posting here. I've thought a lot more about what a good interface for the univariate analysis could look like, and [sunburst plots ](https://plotly.com/python/sunburst-charts/)

In this context, the plot will roughly be a manifestation of the following table, where `color_var = 'X1SCIEFF'`:
```
In[2]:  df_filtered = df[path + [color_var]]
  ...: gr = df_filtered.groupby(by=[x, y])
  ...: gr.count()
Out[2]: 
              X1SCIEFF
X1RACE X1SEX          
1.0    1.0          68
       2.0          54
2.0    1.0         700
       2.0         704
3.0    1.0         834
       2.0         783
4.0    1.0          81
       2.0          63
5.0    1.0        1224
       2.0        1314
6.0    1.0         771
       2.0         796
7.0    1.0          44
       2.0          41
8.0    1.0        4897
       2.0        4890
```

to plot this, though we need it in flattened form (the other dataframe is multi-index). We will also add a mean column:
```
In[1]:  data = gr.count().reset_index().rename(columns={color_var: 'count'})
  ...: mean = gr.mean().reset_index()[color_var]
  ...: data['mean'] = mean
  ...: data
Out[1]: 
    X1RACE  X1SEX  count      mean
0      1.0    1.0     68 -0.065588
1      1.0    2.0     54 -0.048519
2      2.0    1.0    700  0.358714
3      2.0    2.0    704  0.047173
4      3.0    1.0    834  0.219508
5      3.0    2.0    783  0.002899
6      4.0    1.0     81 -0.289877
7      4.0    2.0     63 -0.305873
8      5.0    1.0   1224 -0.000359
9      5.0    2.0   1314 -0.207139
10     6.0    1.0    771  0.209857
11     6.0    2.0    796 -0.059950
12     7.0    1.0     44  0.208409
13     7.0    2.0     41 -0.073171
14     8.0    1.0   4897  0.157692
15     8.0    2.0   4890 -0.081297
```

Here `x = "X1RACE"` and `y = "X1SEX"`. This will be expanded to more than just two variables, so that the user can expand to use as many variables as they would like, and order them in any way they want. So, here is what the frontend will do and expect:

1. From the user, the frontend will get a list `fields` of items to count. It also gets a continuous variable `color_var` that will be used to color each field. It will pass this to the backend and:
2. the backend does the operations noted above and returns the dataframe, `data`

**Comment by Ian-Mint** [comment]
I Should also add, instead of numbers in the categories, .e.g. `'X1RACE'`, We should have a very short category descriptor.

**Comment by SubratoChakravorty** [comment]
Got it. Look at the return_fields method [here](https://github.com/SubratoChakravorty/ECE-229-Group5-final-project/blob/334e27e459d4b85ed98d6a2fac2dec9813cfddc7/src/univariate_methods.py#L4) It returns the all the field ids along with a short text description.

**Comment by Ian-Mint** [comment]
Yeah, I'm using that to populate my dropdown menus, but it needs to be separated into categorical and continuous data, and if possible, the descriptions should be shorter. I noticed some of the fields are pretty complicated, so maybe we just need a lookup table or a hover tip for the user to see what the coded name means.

**Comment by danielyou0230** [comment]
I think we'll just need a predefined *.json for the mapping from variable name to short description, say `'X1RACE'` to `Race`. We can just load the json and return the mapping.

**Comment by SubratoChakravorty** [comment]
@danielyou0230 Can you work on that? Update the return_fields function inside the univariate_methods, I currently have a hardcoded dictionary which has variable name mapped to short description. Can you do something like having the variable name mapped to a short title and descriptionp as some of the descriptions are long to be used in the dropdown. For example,
{'N1GROUP': {'title' : 'Group Work', 'desp': 'Science teacher has students work in small groups'}}.

You can save this as a json file and load it when someone calls the method if you want.

**Comment by danielyou0230** [comment]
> @danielyou0230 Can you work on that? Update the return_fields function inside the univariate_methods, I currently have a hardcoded dictionary which has variable name mapped to short description. Can you do something like having the variable name mapped to a short title and descriptionp as some of the descriptions are too long to be used in the dropdown. For example,
> {'N1GROUP': {'title' : 'Group Work', 'desp': 'Science teacher has students work in small groups'}}.
> 
> You can save this as a json file and load it when someone calls the method if you want.

I'm working on it.
