### ISSUE TITLE
testing!

### ISSUE THREAD

**Issue by Ian-Mint** [SubratoChakravorty/ECE-229-Group5-final-project#22]
We need with 80% coverage.

**Comment by SubratoChakravorty** [comment]
Yes, let's discuss this in today's meeting

**Comment by Ian-Mint** [comment]
OK, this is our current coverage:

![image](https://user-images.githubusercontent.com/6959555/82407769-e59a1c00-9a1e-11ea-9762-0e101cd53145.png)

I've finished the tests for my code and added one test to univariate methods to give you an idea on how to get started.

**Comment by Ian-Mint** [comment]
Instructions on how to run tests are in the README

**Comment by Ian-Mint** [comment]
Test code started. Broken into separate issues:
issue #28 
issue #27
