### ISSUE TITLE
Statiscal test in bivariate anlysis

### ISSUE THREAD

**Issue by Tuclly** [SubratoChakravorty/ECE-229-Group5-final-project#32]
For two categories: we could get the following statistical test or data like:
**mean**, **median**, the **variance** of each category, and for t-test , we could get **P-value** like in 143 project:
![image](https://user-images.githubusercontent.com/57241074/82494189-0e152b00-9a9e-11ea-87a4-9ef1f03e823a.png)

If for more than two categories, we could also do the **ANOVA test**to determine whether there are any statistically significant differences between the means of three or more independent (unrelated) groups, which is also displayed in the 143 project.
![image](https://user-images.githubusercontent.com/57241074/82494448-6c420e00-9a9e-11ea-84be-90e02f53bbf0.png)

And the link for the ANOVA test:

- [https://statistics.laerd.com/statistical-guides/one-way-anova-statistical-guide.php](url)
- [https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.f_oneway.html](url)

**Comment by SubratoChakravorty** [comment]
@Tuclly think of what functions you need for both tests(t and anova) and what parameters the functions should accept and their response format. Once, that is clear communicate with @Ian-Mint and @wangjinjie722 as to how to integrate it with the UI.

**Comment by SubratoChakravorty** [comment]
@Tuclly any update on supporting statistical tests for bivariate analysis?

**Comment by Tuclly** [comment]
For the t-test, we could use the 

> scipy.stats.ttest_ind¶ 
([https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html](url))

- and for the **a,b** parameter, they are the two variables or categories(data set) we need to compare, such as the self-efficiency of the male and female students.

- **axis** is None to compare the whole data array

- **equal_var** and **nan_policy** could be default with any specific parameters.

----------------
For ANOVA test, we could use 

> scipy.stats.f_oneway
([https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.f_oneway.html](url))

- the parameter only has the data array, which are the sample measurements for each group, such as the different kinds of science courses' performance in the self-efficiency in the above plot.

**Comment by SubratoChakravorty** [comment]
Thanks @Tuclly. I used the same functions for my ECE143 project. I meant have you started implementing the function. Look at Issue #38 . The section 1 describes loosely the type of function that we need. Can you implement that function described in Section 1? Then I will handle Section 2 and 3 then. Feel free to ask if you have any doubts. Once the function is ready @Ian-Mint and @wangjinjie722  Can display the function results using appropriate plots or tables.

**Comment by Ian-Mint** [comment]
@SubratoChakravorty, are we still interested in adding these tests?

**Comment by SubratoChakravorty** [comment]
@Tuclly already implemented this module in the backend. I am not sure whether it's there in front end or not. Anyway, it's not super important that it be there in today's video. We can include in this in our final video submission.

**Comment by Ian-Mint** [comment]
OK, got it. I'll see where it makes sense to add them.

**Comment by Ian-Mint** [comment]
closed with commit f42327893d544cb81a24b874f33386e49da649ff
