### ISSUE TITLE
Multivariate analysis V2

### ISSUE THREAD

**Issue by Tuclly** [SubratoChakravorty/ECE-229-Group5-final-project#33]
**1. About the 3D scatter plot:**
![image](https://user-images.githubusercontent.com/57241074/82495032-5aad3600-9a9f-11ea-90ee-6118db6b1b60.png)
![image](https://user-images.githubusercontent.com/57241074/82495142-82040300-9a9f-11ea-9caf-fd1fe057034c.png)

Link:[https://dash-gallery.plotly.host/dash-drug-discovery/](url)

What I mean by the 3D scatter plot is that if we have three categories correlated with each other, like the self-efficiency, gender, with some other discrete variable like the scale of the students' interest in Science(the variable need to be numerical in the axis), so we could draw a very fancy 3D plot to give our user the overview of the correlation or distribution of these three variables in this plot.

**2. About the word cloud and Treemap**
![image](https://user-images.githubusercontent.com/57241074/82495825-9399da80-9aa0-11ea-83fb-24e007bd4d35.png)
![image](https://user-images.githubusercontent.com/57241074/82495836-985e8e80-9aa0-11ea-93a9-7d5b7b51e453.png)
Link: [https://dash-gallery.plotly.host/dash-nlp/](url)
Although these two graphs are applied in the frequencies issues, we could draw the correlation graph, for example, if the user chooses the student's self-efficiency or other outcome variables they expect to see at the top of the table, then the treemap and the word cloud will show the most correlated variable or factors with the variable they have chosen. Both for treemap and word cloud, the size of each square and font-size is 
positively proportional to the scale of the correlation.

--------------------------------
Why recommend word cloud and treemap? 
Being fancy to meet the appetite of the professor, who is a fan of visualization and presentation. ( You must have learnt that from 143 project presentation and his comments in the classroom.)

**Comment by Ian-Mint** [comment]
these are covered by bar plots
