### ISSUE TITLE
Provide names of each category for the categorical data

### ISSUE THREAD

**Issue by Ian-Mint** [SubratoChakravorty/ECE-229-Group5-final-project#39]
We still need labels on all of the categories @SubratoChakravorty @danielyou0230. Let me know if this is implemented already. If not, this needs to be done right away.

**Comment by SubratoChakravorty** [comment]
@Ian-Mint  This was implemented that day itself. If you take a look at the variables.csv, fields such as X1SEX and N1COURSE are replaced by X1GEN and COURSE_TYPE which are the fields with decoded labels. For examples, instead of 1 and 2, it has Male and Female.

**Comment by Ian-Mint** [comment]
It looks like it was implemented for some, but not all of the categorical
data fields like:
N1CONCEPTS
N1GROUP
N1HIDEG
N1INTEREST
N1TERMS
X1RACE
X1TSCERT
X1TSRACE

**Comment by SubratoChakravorty** [comment]
@Ian-Mint  Yeah, for we might drop X1RACE. And most of the other fields are more numerical than categorical. i.e., They are ordinal. You provide a score from 1-5 to a question. @danielyou0230 added them to the categorical. But I am not entirely sure whether they should be numerical or categorical.

**Comment by Ian-Mint** [comment]
I see... I think the ordinal ones should be transferred to continuous,
since they have meaningful mean and variances that will go into the
sunburst and box plots.

For X1RACE, can we just assign the races we know, and put the others into
an "other" category?

**Comment by SubratoChakravorty** [comment]
okay will do close the issue when I am done.

**Comment by Ian-Mint** [comment]
OK, thanks. And note, N1HIDEG at least should probably be considered categorical.

**Comment by SubratoChakravorty** [comment]
Yeah, agree. I will convert only ordinal variables (which have order) to numerical/continuous.
