### ISSUE TITLE
method to return correlation matrix

### ISSUE THREAD

**Issue by Ian-Mint** [SubratoChakravorty/ECE-229-Group5-final-project#43]
For the bivariate analysis, we need a method that returns the correlation matrix:

inputs:
- `fields`: list of continuous variables

outputs:
- pandas dataframe with:
    - `fields` as columns
    - `fields` as indices
    - correlations as values

**Comment by Ian-Mint** [comment]
linked to issue #20

**Comment by SubratoChakravorty** [comment]
I just created a function that does exactly that but since we are handling relations amongst multiple variables, I put it under multivariate_methods.py. Will merge to the master in some time,

**Comment by SubratoChakravorty** [comment]
@Tuclly is creating a function where you have a y variables and multiple continuous x variables let's say x1,x2 and x3.
Then it returns the correlation coefficient of y with each of the x variables. i.e., (r(x1,y), r(x2,y), r(x3,y)) where r(a,b) is the correlation coefficient between a and b.

It is a subset of what the function that he will implement does as it also handles categorical data. Look at #38 Section 1. 

What you asked above is similar to what I described in Section 2, which I just created and will be merging with the master now.

**Comment by Ian-Mint** [comment]
ahhh perfect! that's just what I was picturing.

**Comment by SubratoChakravorty** [comment]
man you weren't kidding when you said you are a refractor. Your messages look so clean and succinct. I am gonna guess your room is always neat and tidy too. haha

**Comment by Ian-Mint** [comment]
haha! I do my best. and it is definitely not clean lol
