### ISSUE TITLE
Modal test is failing

### ISSUE THREAD

**Issue by Ian-Mint** [SubratoChakravorty/ECE-229-Group5-final-project#50]
@wangjinjie722, the modal test keeps failing. I tried to fix it by adding some waits, but it didn't work. The test passes on my machine, but it consistently fails the GitHub automatic tests.

**Comment by wangjinjie722** [comment]
yea, I also tried to fix that. It passes on my laptop but fails on github

**Comment by wangjinjie722** [comment]
Test passed again, online and on Github, without any change of testing code.
