### ISSUE TITLE
Data for sliders - Continuous

### ISSUE THREAD

**Issue by Ian-Mint** [SubratoChakravorty/ECE-229-Group5-final-project#51]
To generate sliders, we need a function that returns the min, max and median for a variable (I think median is a better default than mean).

input:
- field

output
- min, max, median

**Comment by Ian-Mint** [comment]
so I don't have to update my code, can you put this in univariate methods and call it:
`get_stats(field, file_loc)`

**Comment by SubratoChakravorty** [comment]
Got it!

**Comment by danielyou0230** [comment]
Added, please check the commit 2e5dde18fe1a51f522731195469f89a482ff5138

Do you also need to assert that the field is continuous?

**Comment by Ian-Mint** [comment]
no, I'll do that check on my end. Check the other issue I just added.

**Comment by SubratoChakravorty** [comment]
I just did the same @danielyou0230. That's why I replied 'got it' above to indicate I am taking it up. No worries. I will take up the continuous one. Next time, please mention if you are taking up an issue to avoid duplication of work.

**Comment by danielyou0230** [comment]
> I just did the same @danielyou0230. That's why I replied 'got it' above to indicate I am taking it up. No worries. I will take up the continuous one. Next time, please mention if you are taking up an issue to avoid duplication of work.

Sorry for that @SubratoChakravorty , I happen to see the issue and start working on it lol

**Comment by SubratoChakravorty** [comment]
Yeah, no worries.
