### ISSUE TITLE
Data for sliders - Categorical

### ISSUE THREAD

**Issue by Ian-Mint** [SubratoChakravorty/ECE-229-Group5-final-project#53]
For categorical data, we need something similar to continuous (issue #51), but a little bit more complicated. I will filter for continuous/categorical on my end and there should be two separate functions. this one can be:

`def get_categories(field, file_loc) -> Tuple[int, dict]`
input:
- field
- file location

output:
- most common category as an `int`
- a dictionary mapping category numbers to category values

**Comment by SubratoChakravorty** [comment]
Will do!

**Comment by SubratoChakravorty** [comment]
added get_categories lemme know that works for you.

**Comment by Ian-Mint** [comment]
I don't think it's pushed to master.

**Comment by SubratoChakravorty** [comment]
I created a pull request with you as the reviewer
