### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by Ian-Mint** [SubratoChakravorty/ECE-229-Group5-final-project#63]
Setup.py is incomplete. It should either be completed or removed. It would be nice to have it, but it's not a necessity.

**Comment by SubratoChakravorty** [comment]
Pycharm automatically adds libraries to setup.py. Should not be too difficult to have it.

**Comment by wangjinjie722** [comment]
Yea, I just use it for vscode. I complete the setup.py. Then got a new issue after I run python3 setup.py install

**Comment by wangjinjie722** [comment]
setup works well now
