### ISSUE TITLE
correlation matrix heat map

### ISSUE THREAD

**Issue by SubratoChakravorty** [SubratoChakravorty/ECE-229-Group5-final-project#68]
update the heat map to cover all numerical variables or use a dropdown to select variables for plotting correlation heat map. additionally add a drop down to select from pearson, spearman or kendall, i have updated the function to accept a method parameter which accepts the method of correlation which can be either 'pearson', 'spearman' or 'kendall'. default is pearson.

**Comment by Ian-Mint** [comment]
currently, the heatmap does include all categorical variables:
```python
correlation_matrix = get_correlation_matrix(vars_df.loc[vars_df['type'] == 'continuous'].index.to_list(),
                                            student_data_file)
```

Considering our user story, I'm not sure it makes sense to allow them to pick which type of correlation test they want without giving a significant explanation about what each test means. My preference would be just to pick our favorite test and serve only that one.

**Comment by Ian-Mint** [comment]
spearman:
![image](https://user-images.githubusercontent.com/6959555/83584950-6ec05100-a4fd-11ea-98ef-ceffb00ce99a.png)

Kendall:
![image](https://user-images.githubusercontent.com/6959555/83584984-83044e00-a4fd-11ea-8e1e-f092803d000b.png)

Pearson:
![image](https://user-images.githubusercontent.com/6959555/83585012-96afb480-a4fd-11ea-9b5d-9bec44fd82cb.png)

Spearman appears to provide the best contrast, but there isn't a lot of difference between them. I'll use spearman for now.

**Comment by Ian-Mint** [comment]
@SubratoChakravorty, Sorry, to be resistant on the dropdown menu, but thinking about it more, it doesn't make sense to have a selectable heat map AND a feature importance bar plot. 

I think the purpose of the heatmap should be for the user to be able to look at all of the variables at once without going through the full dropdown menu. It's not ideal that all the values aren't displayed on the axes, but they can get the values using the hover.

What are your thoughts?

**Comment by SubratoChakravorty** [comment]
Hey,

I see your point regarding not providing user with the option of selecting the method of correlation. I believe they do need to have some idea about the statistical concepts used in our dashboard otherwise they won't be a perfect user. Ideally, we have a dropdown with method of correlation if the user understands what they mean, he/she may use it lest they won't.
Anyway I am perfectly fine with using our discretion for which correlation should be used. Don't have any strong feeling for either. If you feel that's the best way to, feel free.

Regarding dropdown menu for correlation heat map, having all the variables on a single heat map makes it cluttered and difficult to observe patterns. The way I thought about it was to first use the right side bar plot to see which fields are highly correlated with your y variable. Once you know that, you use the correlation heat map to see if they are some highly correlated variables among them. 
The dashboard currently does that in reverse, you first see which values are highly correlate with each other and then select a set of variables for the right side bar plot. This picture works well with having all the variables on the heat map at once as long as it is easy to discern patterns.
So, having all the variables on the heat map seems good just make sure all the field names are visible on the axes.
